-- MySQL Script generated by MySQL Workbench
-- Wed Mar  4 23:23:52 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema coffee_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coffee_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coffee_db` DEFAULT CHARACTER SET utf8 ;
USE `coffee_db` ;

-- -----------------------------------------------------
-- Table `coffee_db`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`region` (
  `region_id` INT NOT NULL,
  `region_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`region_id`),
  UNIQUE INDEX `region_id_UNIQUE` (`region_id` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `coffee_db`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`province` (
  `province_id` INT NOT NULL,
  `province_name` VARCHAR(45) NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`province_id`),
  UNIQUE INDEX `province_id_UNIQUE` (`province_id` ASC) VISIBLE,
  INDEX `fk_province_region_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `fk_province_region`
    FOREIGN KEY (`region_id`)
    REFERENCES `coffee_db`.`region` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`city` (
  `city_id` INT NOT NULL,
  `city_name` VARCHAR(45) NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `city_id_UNIQUE` (`city_id` ASC) VISIBLE,
  INDEX `fk_city_region_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `fk_city_region`
    FOREIGN KEY (`region_id`)
    REFERENCES `coffee_db`.`region` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`supplier` (
  `supplier_id` INT NOT NULL,
  `supplier_name` VARCHAR(100) NOT NULL,
  `contact_number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `address` VARCHAR(255) NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`supplier_id`),
  UNIQUE INDEX `supplier_id_UNIQUE` (`supplier_id` ASC) VISIBLE,
  INDEX `fk_supplier_province1_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_province1`
    FOREIGN KEY (`province_id`)
    REFERENCES `coffee_db`.`province` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`coffee_bean`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`coffee_bean` (
  `bean_id` INT NOT NULL,
  `bean_name` VARCHAR(100) NOT NULL,
  `variety` VARCHAR(100) NULL,
  `origin_province_id` INT NOT NULL,
  PRIMARY KEY (`bean_id`),
  UNIQUE INDEX `bean_id_UNIQUE` (`bean_id` ASC) VISIBLE,
  INDEX `fk_coffee_bean_province1_idx` (`origin_province_id` ASC) VISIBLE,
  CONSTRAINT `fk_coffee_bean_province1`
    FOREIGN KEY (`origin_province_id`)
    REFERENCES `coffee_db`.`province` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`store` (
  `store_id` INT NOT NULL,
  `store_name` VARCHAR(100) NOT NULL,
  `contact_number` VARCHAR(45) NULL,
  `address` VARCHAR(150) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`store_id`),
  UNIQUE INDEX `store_id_UNIQUE` (`store_id` ASC) VISIBLE,
  INDEX `fk_store_city1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_store_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `coffee_db`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`customer` (
  `customer_id` INT NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `contact_number` VARCHAR(45) NULL,
  `address` VARCHAR(150) NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC) VISIBLE,
  INDEX `fk_customer_city1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `coffee_db`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`currency` (
  `currency_code` VARCHAR(5) NOT NULL,
  `currency_name` VARCHAR(45) NULL,
  `symbol` VARCHAR(5) NULL,
  PRIMARY KEY (`currency_code`),
  UNIQUE INDEX `currency_code_UNIQUE` (`currency_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`exchange_rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`exchange_rate` (
  `rate_id` INT NOT NULL AUTO_INCREMENT,
  `from_currency_code` VARCHAR(5) NOT NULL,
  `to_currency_code` VARCHAR(5) NOT NULL,
  `exchange_rate` DECIMAL(18,6) NULL,
  `effective_date` DATE NULL,
  PRIMARY KEY (`rate_id`),
  INDEX `fk_exchange_rate_currency1_idx` (`from_currency_code` ASC) VISIBLE,
  INDEX `fk_exchange_rate_currency2_idx` (`to_currency_code` ASC) VISIBLE,
  CONSTRAINT `fk_exchange_rate_currency1`
    FOREIGN KEY (`from_currency_code`)
    REFERENCES `coffee_db`.`currency` (`currency_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exchange_rate_currency2`
    FOREIGN KEY (`to_currency_code`)
    REFERENCES `coffee_db`.`currency` (`currency_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`sale` (
  `sale_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `sale_date` DATE NULL,
  `total_amount` DECIMAL(18,2) NULL,
  `currency_code` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`sale_id`),
  INDEX `fk_sales_store1_idx` (`store_id` ASC) VISIBLE,
  INDEX `fk_sales_customer1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_sales_currency1_idx` (`currency_code` ASC) VISIBLE,
  CONSTRAINT `fk_sales_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `coffee_db`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `coffee_db`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_currency1`
    FOREIGN KEY (`currency_code`)
    REFERENCES `coffee_db`.`currency` (`currency_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`sale_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`sale_items` (
  `sale_items_id` INT NOT NULL,
  `sale_id` INT NOT NULL,
  `bean_bean_id` INT NOT NULL,
  `quantity` INT NULL,
  `unit_price` DECIMAL(18,2) NULL,
  `subtotal` DECIMAL(18,2) NULL,
  PRIMARY KEY (`sale_items_id`),
  INDEX `fk_sales_items_sales1_idx` (`sale_id` ASC) VISIBLE,
  INDEX `fk_sales_items_coffee_bean1_idx` (`bean_bean_id` ASC) VISIBLE,
  CONSTRAINT `fk_sales_items_sales1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `coffee_db`.`sale` (`sale_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_items_coffee_bean1`
    FOREIGN KEY (`bean_bean_id`)
    REFERENCES `coffee_db`.`coffee_bean` (`bean_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`store_inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`store_inventory` (
  `inventory_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `bean_bean_id` INT NOT NULL,
  `quantity_kg` INT NULL,
  `last_updated` DATE NULL,
  PRIMARY KEY (`inventory_id`),
  INDEX `fk_store_inventory_store1_idx` (`store_id` ASC) VISIBLE,
  INDEX `fk_store_inventory_coffee_bean1_idx` (`bean_bean_id` ASC) VISIBLE,
  CONSTRAINT `fk_store_inventory_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `coffee_db`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_store_inventory_coffee_bean1`
    FOREIGN KEY (`bean_bean_id`)
    REFERENCES `coffee_db`.`coffee_bean` (`bean_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`supplier_inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`supplier_inventory` (
  `supplier_inv_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `bean_id` INT NOT NULL,
  `quantity_kg` INT NULL,
  `cost_per_kg` DECIMAL(18,2) NULL,
  `currency_code` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`supplier_inv_id`),
  INDEX `fk_supplier_inventory_supplier1_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `fk_supplier_inventory_coffee_bean1_idx` (`bean_id` ASC) VISIBLE,
  INDEX `fk_supplier_inventory_currency1_idx` (`currency_code` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_inventory_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `coffee_db`.`supplier` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_inventory_coffee_bean1`
    FOREIGN KEY (`bean_id`)
    REFERENCES `coffee_db`.`coffee_bean` (`bean_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_inventory_currency1`
    FOREIGN KEY (`currency_code`)
    REFERENCES `coffee_db`.`currency` (`currency_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`restock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`restock` (
  `restock_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `restock_date` DATE NULL,
  `currency_code` VARCHAR(5) NOT NULL,
  `total_amount` DECIMAL(18,2) NULL,
  PRIMARY KEY (`restock_id`),
  INDEX `fk_restock_store1_idx` (`store_id` ASC) VISIBLE,
  INDEX `fk_restock_supplier1_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `fk_restock_currency1_idx` (`currency_code` ASC) VISIBLE,
  CONSTRAINT `fk_restock_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `coffee_db`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restock_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `coffee_db`.`supplier` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restock_currency1`
    FOREIGN KEY (`currency_code`)
    REFERENCES `coffee_db`.`currency` (`currency_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`restock_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`restock_items` (
  `restock_id` INT NOT NULL,
  `bean_bean_id` INT NOT NULL,
  `quantity` INT NULL,
  `unit_cost` DECIMAL(18,2) NULL,
  `subtotal` DECIMAL(18,2) NULL,
  INDEX `fk_restock_items_restock1_idx` (`restock_id` ASC) VISIBLE,
  PRIMARY KEY (`restock_id`, `bean_bean_id`),
  INDEX `fk_restock_items_coffee_bean1_idx` (`bean_bean_id` ASC) VISIBLE,
  CONSTRAINT `fk_restock_items_restock1`
    FOREIGN KEY (`restock_id`)
    REFERENCES `coffee_db`.`restock` (`restock_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restock_items_coffee_bean1`
    FOREIGN KEY (`bean_bean_id`)
    REFERENCES `coffee_db`.`coffee_bean` (`bean_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`sale_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`sale_payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `sale_id` INT NOT NULL,
  `payment_date` DATE NULL,
  `amount_paid` DECIMAL(18,2) NULL,
  `currency_code` VARCHAR(5) NOT NULL,
  `payment_method` ENUM('CASH', 'CARD', 'BANK TRANSFER', 'CHEQUE') NULL,
  `payment_status` VARCHAR(45) NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_sale_payment_sale1_idx` (`sale_id` ASC) VISIBLE,
  INDEX `fk_sale_payment_currency1_idx` (`currency_code` ASC) VISIBLE,
  CONSTRAINT `fk_sale_payment_sale1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `coffee_db`.`sale` (`sale_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_payment_currency1`
    FOREIGN KEY (`currency_code`)
    REFERENCES `coffee_db`.`currency` (`currency_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee_db`.`restock_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_db`.`restock_payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `restock_id` INT NOT NULL,
  `payment_date` DATE NULL,
  `amount_paid` DECIMAL(18,2) NULL,
  `currency_code` VARCHAR(5) NOT NULL,
  `payment_method` ENUM('CASH', 'CARD', 'BANK TRANSFER', 'CHEQUE') NULL,
  `payment_status` VARCHAR(45) NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_restock_payment_restock1_idx` (`restock_id` ASC) VISIBLE,
  INDEX `fk_restock_payment_currency1_idx` (`currency_code` ASC) VISIBLE,
  CONSTRAINT `fk_restock_payment_restock1`
    FOREIGN KEY (`restock_id`)
    REFERENCES `coffee_db`.`restock` (`restock_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restock_payment_currency1`
    FOREIGN KEY (`currency_code`)
    REFERENCES `coffee_db`.`currency` (`currency_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
